### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by tbrittoborges** [dieterich-lab/dorina#5]
Python 3.6 is the latest stable version of Python programming language. It's more secure and generally faster than Python 2.7. 
This issue aims to refactor dorina and webdorina code for py36 without dropping py27 support.

**Comment by al2na** [comment]
I would coordinate any update with @rekado who has his own plans to improve dorina

**Comment by CDieterich** [comment]
Sure, let's have this discussion. @rekado ?

**Comment by rekado** [comment]
Originally, I was planning to move away from Python for the purpose of integrating the features of Dorina with other tools that we have developed here.  This would mean to switch to R and Scheme.

What are your plans with Carina/Dorina 3?

**Comment by CDieterich** [comment]
Great to hear from you after such a long time.

Switching languages in not an option for us.

Please fork or build something entirely new.

All best wishes,

Christoph
